export const apiUrl = "http://localhost:8080/api";

// Actions
export const FETCHING_CITIES = "FETCHING_CITIES";
export const FETCHING_CITIES_SUCCESS = "FETCHING_CITIES_SUCCESS";
export const FETCHING_CITIES_FAILURE = "FETCHING_CITIES_FAILURE";
export const FETCHING_COUNTRIES = "FETCHING_COUNTRIES";
export const FETCHING_COUNTRIES_SUCCESS = "FETCHING_COUNTRIES_SUCCESS";
export const FETCHING_COUNTRIES_FAILURE = "FETCHING_COUNTRIES_FAILURE";
